

OPT = -O2
STD = -std=c++17
GCC = g++ $(OPT) $(STD)

BIN = genetic_drawing 
OUT = -o $(BIN)

SRC = main.cpp 
INCLUDE = 
FILES = $(SRC) $(INCLUDE)

genetic: $(FILES)
	$(GCC) $(OUT) $(SRC)


clean:
	rm $(BIN)
